/* The channel-age strip.
 *
 * Permanent, not a tooltip. This is the whole honesty-about-latency mechanism:
 * MOSDAC Level 1 imagery sits on a three-day tier for a general account, and
 * that fact belongs on the screen rather than in a footnote. A viewer looking
 * at this strip can see, without asking, that the infrared is three days old
 * and the Level 2 products are twenty minutes old.
 *
 * The visual reference is the ticker along the top of the dashboard in the
 * reference footage: a dense horizontal run of monospace readouts, each with a
 * label and a number, scrolling if it overflows rather than truncating. A
 * channel that scrolls out of view still exists; a channel that was truncated
 * away looks like a channel that was never there.
 */

import { useEffect, useRef, useState } from "react";
import { formatAge } from "../api/client";
import type { Freshness, FreshnessChannel } from "../api/types";

const LABEL: Record<string, string> = {
  ir: "IR", wv: "WV", vis: "VIS", olr: "OLR", pmw89: "PMW89",
  pmw37: "PMW37", scat: "SCAT", soil: "SOIL", land: "LAND",
};

function colourFor(c: FreshnessChannel): string {
  if (!c.present) return "var(--fg-3)";
  switch (c.status) {
    case "expired":
      return "var(--alert)";
    case "stale":
      return "var(--replay)";
    default:
      return "var(--ok)";
  }
}

function valueFor(c: FreshnessChannel): string {
  if (!c.present) {
    // The three absent states read differently, because they are different
    // facts and a forecaster needs to tell them apart.
    if (c.status === "no_coverage") return "no swath";
    if (c.status === "instrument_unavailable") return "night";
    return "absent";
  }
  if (c.status === "expired") return "NO DATA";
  return formatAge(c.age_minutes);
}

interface Props {
  freshness: Freshness | null;
  compact?: boolean;
}

export default function ChannelAgeStrip({ freshness, compact = false }: Props) {
  const scroller = useRef<HTMLDivElement>(null);
  const [overflowing, setOverflowing] = useState(false);

  useEffect(() => {
    const el = scroller.current;
    if (!el) return;
    const check = () => setOverflowing(el.scrollWidth > el.clientWidth + 4);
    check();
    const ro = new ResizeObserver(check);
    ro.observe(el);
    return () => ro.disconnect();
  }, [freshness]);

  if (!freshness) {
    return (
      <div className="tele" style={{ padding: "6px 12px" }}>
        channel age: loading…
      </div>
    );
  }

  const channels = freshness.channels.filter((c) => c.channel !== "land");

  return (
    <div
      style={{
        display: "flex", alignItems: "center", gap: 12,
        padding: compact ? "5px 10px" : "6px 12px",
        borderTop: "1px solid var(--line)",
        background: "var(--bg-1)", minHeight: 28, overflow: "hidden",
      }}
    >
      <span className="tele" style={{ flex: "none", color: "var(--fg-2)" }}>
        Channel age
      </span>

      <div
        ref={scroller}
        className="scroll-x stagger"
        style={{
          display: "flex", alignItems: "center", gap: 14, flex: 1,
          scrollbarWidth: "none", maskImage: overflowing
            ? "linear-gradient(90deg, transparent, #000 12px, #000 calc(100% - 24px), transparent)"
            : undefined,
        }}
      >
        {channels.map((c) => (
          <span
            key={c.channel}
            title={c.reason ?? `${c.channel}: ${c.status}`}
            style={{
              display: "inline-flex", alignItems: "baseline", gap: 5,
              flex: "none", whiteSpace: "nowrap",
              opacity: c.present ? 1 : 0.62,
            }}
          >
            <span className="tele" style={{ color: "var(--fg-2)" }}>
              {LABEL[c.channel] ?? c.channel.toUpperCase()}
            </span>
            <span
              className="num"
              style={{ fontSize: 11, color: colourFor(c), letterSpacing: "0.01em" }}
            >
              {valueFor(c)}
            </span>
          </span>
        ))}
      </div>

      {/* The tier note, which is the sentence that turns an access constraint
          into the architectural claim. */}
      <span
        className="tele"
        style={{ flex: "none", color: "var(--fg-3)" }}
        title={freshness.tier_note}
      >
        {freshness.tier === "live" ? "L2 NRT · L1 3-day tier" : `${freshness.tier} tier`}
      </span>

      {freshness.synthetic_imagery && (
        <span
          className="tele"
          style={{ flex: "none", color: "var(--warn)" }}
          title="Gridded fields are generated by the project's parametric forward model. Positions and intensity labels are real IBTrACS best-track."
        >
          Synthetic imagery
        </span>
      )}
    </div>
  );
}
