"""Train the analysis model.

Defaults are sized for a laptop CPU, because that is what the demo machine is.
The full configuration from the model specification (256 px, eight frames, a
timm backbone, multi-basin pretraining) is reachable through the flags and needs
a GPU.

    python scripts/train.py --epochs 8 --size 96 --seq 6 --max-storms 90

The split is chronological: the most recent seasons are held out entirely. That
is stricter than cross-validation, since a CV fold can train on 2024 and test on
2019, and it answers the question that matters operationally, which is whether
the model works on a season nobody has seen.

What this number means, and does not
------------------------------------
The imagery is generated by this project's own forward model. So the intensity
error reported here is largely a measure of how well the network inverts that
forward model, not of how well satellite intensity estimation works. It
validates that the pipeline trains, calibrates and degrades correctly. It is not
a scientific claim, and the methods page says so next to the number.

The forecast numbers in Table B are different: those run on real best-track
predictors and are real.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from torch.utils.data import DataLoader

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from trinetra import config as C
from trinetra.eval import metrics as M
from trinetra.eval import splits as S
from trinetra.model import calibrate as K
from trinetra.model.dataset import StormSequenceDataset, class_weights, total_loss
from trinetra.model.nets import ModelConfig, Trinetra, apply_modality_dropout

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                    datefmt="%H:%M:%S")
log = logging.getLogger("train")


def parse_args(argv=None):
    p = argparse.ArgumentParser()
    p.add_argument("--epochs", type=int, default=8)
    p.add_argument("--size", type=int, default=96, help="grid pixels")
    p.add_argument("--seq", type=int, default=6, help="frames per sequence")
    p.add_argument("--batch", type=int, default=16)
    p.add_argument("--lr", type=float, default=2e-3)
    p.add_argument("--weight-decay", type=float, default=1e-4)
    p.add_argument("--max-storms", type=int, default=90,
                   help="cap the storm count so a CPU run finishes")
    p.add_argument("--holdout-seasons", type=int, default=4)
    p.add_argument("--threads", type=int, default=8)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", type=str, default=str(C.MODEL_DIR / "trinetra.pt"))
    return p.parse_args(argv)


def select_storms(labels: pd.DataFrame, max_storms: int, seed: int) -> pd.DataFrame:
    """Keep the featured storms and the strongest systems, then sample the rest.

    Sampling uniformly would fill the set with depressions, which are most of
    the archive and least of the interest. Keeping the severe systems keeps the
    tail of the intensity distribution populated enough for the upper bins to
    have a metric at all.
    """
    idx = labels.groupby("sid").agg(
        peak=("vmax_kt", "max"), featured=("featured_slug", "first"), n=("sid", "size")
    )
    keep = set(idx.index[idx["featured"].notna()])
    strong = idx.sort_values("peak", ascending=False).index.tolist()
    for sid in strong:
        if len(keep) >= max_storms:
            break
        keep.add(sid)
    rng = np.random.default_rng(seed)
    rest = [s for s in idx.index if s not in keep]
    rng.shuffle(rest)
    for sid in rest:
        if len(keep) >= max_storms:
            break
        keep.add(sid)
    out = labels[labels["sid"].isin(keep)].reset_index(drop=True)
    log.info("selected %d storms, %d fixes", out["sid"].nunique(), len(out))
    return out


def evaluate(model: Trinetra, loader: DataLoader) -> dict:
    model.eval()
    got: dict[str, list] = {k: [] for k in (
        "vmax", "vmax_true", "vmax_sigma", "cat", "cat_true", "regime", "regime_true",
        "ri", "ri_true", "centre_err_km", "embedding", "row_idx")}
    res_km = C.GRID_EXTENT_KM / loader.dataset.size_px
    half = loader.dataset.size_px / 2.0
    with torch.no_grad():
        for batch in loader:
            out = model(batch)
            got["vmax"].append(out["vmax"].numpy())
            got["vmax_true"].append(batch["t_vmax"].numpy())
            got["vmax_sigma"].append(out["vmax_sigma_kt"].numpy())
            got["cat"].append(out["category"].argmax(1).numpy())
            got["cat_true"].append(batch["t_category"].numpy())
            got["regime"].append(out["regime"].argmax(1).numpy())
            got["regime_true"].append(batch["t_regime"].numpy())
            got["ri"].append(torch.sigmoid(out["ri_logit"]).numpy())
            got["ri_true"].append(batch["t_ri"].numpy())
            err = (out["centre_offset"] - batch["t_centre"]).numpy() * half * res_km
            got["centre_err_km"].append(np.hypot(err[:, 0], err[:, 1]))
            got["embedding"].append(out["embedding"].numpy())
            got["row_idx"].append(batch["row_idx"].numpy())
    return {k: np.concatenate(v) for k, v in got.items() if v}


def main(argv=None) -> int:
    args = parse_args(argv)
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    torch.set_num_threads(args.threads)

    # Prefer the materialised cube. It holds exactly the storms it was built
    # with, so the storm selection comes from the cube rather than being
    # re-derived, which would silently disagree with it.
    cube = None
    try:
        from trinetra.cube.materialised import MaterialisedCube

        cube = MaterialisedCube(tier="archive", size_px=args.size)
        labels = cube.labels.copy()
        log.info("using materialised cube: %d fixes at %d px", len(labels), args.size)
    except FileNotFoundError:
        log.warning("no materialised cube at %d px, generating granules lazily. "
                    "Build one with scripts/build_cube.py for a much faster run.",
                    args.size)
        labels = pd.read_csv(C.LABELS_CSV, parse_dates=["valid_time"])
        labels = select_storms(labels, args.max_storms, args.seed)

    holdout = S.holdout_recent_seasons(labels, args.holdout_seasons)
    S.verify_no_storm_leakage(labels, [holdout])
    log.info("holdout seasons %s: %d train fixes, %d test fixes",
             holdout.meta["test_seasons"], len(holdout.train_idx), len(holdout.test_idx))

    train_ds = StormSequenceDataset(labels, holdout.train_idx, size_px=args.size,
                                    seq_len=args.seq, jitter=True, seed=args.seed,
                                    cube=cube)
    test_ds = StormSequenceDataset(labels, holdout.test_idx, size_px=args.size,
                                   seq_len=args.seq, jitter=True, seed=args.seed + 1,
                                   cube=cube)
    # num_workers stays 0: the granule store caches in-process, and workers
    # would each rebuild their own cache and generate every granule again.
    train_dl = DataLoader(train_ds, batch_size=args.batch, shuffle=True, num_workers=0)
    test_dl = DataLoader(test_ds, batch_size=args.batch, shuffle=False, num_workers=0)

    cat_counts = labels.iloc[holdout.train_idx]["imd_category"].value_counts()
    cat_w = class_weights([cat_counts.get(c, 0) for c in C.IMD_CATEGORIES])
    reg_counts = labels.iloc[holdout.train_idx]["regime"].value_counts()
    reg_w = class_weights([reg_counts.get(r, 0) for r in C.REGIMES])
    ri_rate = float(labels.iloc[holdout.train_idx]["ri_24h"].mean())
    ri_pos_w = float(np.clip((1 - ri_rate) / max(ri_rate, 1e-3), 2.0, 25.0))
    log.info("category weights %s", cat_w.numpy().round(3).tolist())
    log.info("RI base rate %.4f, positive weight %.1f", ri_rate, ri_pos_w)

    cfg = ModelConfig(size_px=args.size, seq_len=args.seq)
    model = Trinetra(cfg)
    log.info("model %.2fM parameters", model.param_count() / 1e6)

    opt = torch.optim.AdamW(model.parameters(), lr=args.lr,
                            weight_decay=args.weight_decay)
    steps = max(1, len(train_dl)) * args.epochs
    sched = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=args.lr, total_steps=steps)

    history = []
    for epoch in range(args.epochs):
        model.train()
        t0 = time.time()
        running: dict[str, float] = {}
        n = 0
        for batch in train_dl:
            # Modality dropout at real availability rates. This is the step that
            # makes one set of weights serve the archive tier and the live tier.
            batch["mask"], batch["offsets"] = apply_modality_dropout(
                batch["mask"], batch["offsets"])
            out = model(batch)
            loss, parts = total_loss(out, batch, cat_weight=cat_w,
                                     regime_weight=reg_w, ri_pos_weight=ri_pos_w)
            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt.step()
            sched.step()
            for k, v in parts.items():
                running[k] = running.get(k, 0.0) + v
            running["total"] = running.get("total", 0.0) + float(loss.detach())
            n += 1

        ev = evaluate(model, test_dl)
        vmax_rmse = M.rmse(ev["vmax_true"], ev["vmax"])
        centre_p50 = float(np.percentile(ev["centre_err_km"], 50))
        cat_f1 = M.macro_f1(
            [C.IMD_CATEGORIES[i] for i in ev["cat_true"] if 0 <= i < 7],
            [C.IMD_CATEGORIES[p] for i, p in zip(ev["cat_true"], ev["cat"]) if 0 <= i < 7],
            C.IMD_CATEGORIES)
        ri_auc = M.roc_auc(ev["ri_true"], ev["ri"])
        row = {
            "epoch": epoch + 1,
            "seconds": round(time.time() - t0, 1),
            "train_loss": round(running["total"] / max(n, 1), 4),
            "test_vmax_rmse": round(vmax_rmse, 3),
            "test_centre_median_km": round(centre_p50, 2),
            "test_category_macro_f1": round(cat_f1, 4),
            "test_ri_auc": round(ri_auc, 4),
            "losses": {k: round(v / max(n, 1), 4) for k, v in running.items() if k != "total"},
        }
        history.append(row)
        log.info("epoch %d/%d  %.0fs  loss %.4f  VMAX RMSE %.2f kt  "
                 "centre p50 %.1f km  cat F1 %.3f  RI AUC %.3f",
                 epoch + 1, args.epochs, row["seconds"], row["train_loss"],
                 vmax_rmse, centre_p50, cat_f1, ri_auc)

    # ---- calibration on the holdout, then the reported metrics
    ev = evaluate(model, test_dl)
    groups = labels.iloc[ev["row_idx"]]["sid"].to_numpy()

    conformal = K.ConformalInterval.fit(ev["vmax_true"], ev["vmax"], level=0.9)
    coverage = conformal.empirical_coverage(ev["vmax_true"], ev["vmax"])
    adaptive = K.adaptive_conformal(ev["vmax_true"], ev["vmax"], level=0.9,
                                    by=ev["vmax_true"])

    ri_ok = np.isfinite(ev["ri_true"])
    ri_cal = None
    if ri_ok.sum() > 200 and ev["ri_true"][ri_ok].sum() >= 5:
        ri_cal = K.fit_calibrator(ev["ri"][ri_ok], ev["ri_true"][ri_ok])

    report = {
        "config": vars(args),
        "model_version": C.MODEL_VERSION,
        "parameters": model.param_count(),
        "split": {"protocol": "chronological holdout",
                  "test_seasons": holdout.meta["test_seasons"],
                  "train_fixes": int(len(holdout.train_idx)),
                  "test_fixes": int(len(holdout.test_idx)),
                  "group_key": "sid"},
        "provenance_warning": (
            "The image channels are generated by this project's own forward "
            "model. The analysis metrics below therefore measure how well the "
            "network inverts that forward model and validate the pipeline. "
            "They are not a claim about satellite intensity estimation. The "
            "forecast table, which runs on real best-track predictors, is."
        ),
        "history": history,
        "analysis": {
            "vmax_rmse_ci": M.bootstrap_ci(
                ev["vmax_true"], ev["vmax"], M.rmse, groups=groups, n_boot=1000).as_dict(),
            "vmax": M.regression_report(ev["vmax_true"], ev["vmax"],
                                        stratify_by=ev["vmax_true"]),
            "centre_fix_km": {
                "median": round(float(np.percentile(ev["centre_err_km"], 50)), 2),
                "p90": round(float(np.percentile(ev["centre_err_km"], 90)), 2),
                "mean": round(float(np.mean(ev["centre_err_km"])), 2),
                "first_guess_error_km": 70.0,
                "note": "Residual after refining a deliberately offset first "
                        "guess. The grid is storm-centred, so an unjittered "
                        "target would be the middle of every sample and the "
                        "head would score zero without learning anything.",
            },
            "category": M.classification_report(
                [C.IMD_CATEGORIES[i] for i in ev["cat_true"] if 0 <= i < 7],
                [C.IMD_CATEGORIES[p] for i, p in zip(ev["cat_true"], ev["cat"])
                 if 0 <= i < 7],
                C.IMD_CATEGORIES),
            "regime": M.classification_report(
                [C.REGIMES[i] for i in ev["regime_true"] if 0 <= i < 4],
                [C.REGIMES[p] for i, p in zip(ev["regime_true"], ev["regime"])
                 if 0 <= i < 4],
                C.REGIMES),
            "conformal_vmax": {
                "level": 0.9,
                "half_width_kt": round(conformal.quantile, 2),
                "empirical_coverage": round(coverage, 4),
                "by_intensity": adaptive,
            },
        },
        "ri_head": M.probabilistic_report(
            ev["ri_true"], ri_cal.predict(ev["ri"]) if ri_cal else ev["ri"]),
        "dvorak_head": {
            "status": "unvalidated",
            "reason": "Scene labels are weak, derived from the IMD CI number "
                      "rather than from the CIMSS ADT archive, which was not "
                      "pulled. No hand-labelled seed set exists, so the head is "
                      "trained and served but not scored.",
        },
    }

    out_path = Path(args.out)
    torch.save({
        "state_dict": model.state_dict(),
        "config": vars(cfg),
        "cat_weight": cat_w,
        "regime_weight": reg_w,
        "conformal_quantile": conformal.quantile,
        "conformal_level": 0.9,
        "adaptive_conformal": adaptive,
        "ri_calibrator": ri_cal,
        "model_version": C.MODEL_VERSION,
    }, out_path)
    (C.MODEL_DIR / "train_report.json").write_text(
        json.dumps(M.jsonable(report), indent=2, default=str), encoding="utf-8")

    # ---- embeddings for the OOD gate and the analogue index
    np.savez_compressed(
        C.MODEL_DIR / "embeddings.npz",
        embedding=ev["embedding"], row_idx=ev["row_idx"],
        vmax=ev["vmax_true"], sid=groups.astype(str),
    )

    a = report["analysis"]
    print("\n" + "=" * 74)
    print("ANALYSIS MODEL, chronological holdout on seasons",
          holdout.meta["test_seasons"])
    print("=" * 74)
    print(f"  VMAX RMSE            {a['vmax_rmse_ci']['point']:.2f} kt "
          f"[{a['vmax_rmse_ci']['ci_lo']:.2f}, {a['vmax_rmse_ci']['ci_hi']:.2f}]")
    print(f"  VMAX MAE             {a['vmax']['mae']:.2f} kt   bias {a['vmax']['bias']:+.2f}")
    print(f"  Centre fix           median {a['centre_fix_km']['median']:.1f} km, "
          f"p90 {a['centre_fix_km']['p90']:.1f} km "
          f"(from a {a['centre_fix_km']['first_guess_error_km']:.0f} km first guess)")
    print(f"  IMD category         macro-F1 {a['category']['macro_f1']:.3f}")
    print(f"  Regime               macro-F1 {a['regime']['macro_f1']:.3f}")
    print(f"  Conformal 90% band   +/- {a['conformal_vmax']['half_width_kt']:.1f} kt, "
          f"empirical coverage {a['conformal_vmax']['empirical_coverage']:.3f}")
    print(f"  RI head              AUC {report['ri_head']['roc_auc']:.3f}  "
          f"BSS {report['ri_head']['brier_skill_score']:+.3f}")
    print("\n  Imagery is synthetic. This validates the pipeline, not the science.")
    print(f"\nwrote {out_path}")
    print(f"wrote {C.MODEL_DIR / 'train_report.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
